# Generated by Django 3.2.5 on 2021-07-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_surtido', models.DateTimeField(null=True)),
                ('urgente', models.BooleanField(default=False)),
                ('tipo_pedido', models.CharField(choices=[('1', 'CENTRO DISTRIBUCION'), ('2', 'SUCURSAL'), ('3', 'EMPRESA ASOCIADA')], max_length=19)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('codigo_sucursal', models.IntegerField()),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, to='lista_pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaAsociada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('codigo_socio', models.IntegerField()),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, to='lista_pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_articulos', models.IntegerField()),
                ('articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.PROTECT, to='articulos.articulo')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, to='lista_pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='CentroDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.CharField(max_length=50)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.PROTECT, to='lista_pedidos.pedido')),
            ],
        ),
    ]
