# Generated by Django 3.2.5 on 2021-07-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.IntegerField(null=True)),
                ('fotografia', models.ImageField(upload_to='uploads/')),
                ('direccion', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(choices=[('NORMAL', 'NORMAL'), ('PLATA', 'PLATA'), ('ORO', 'ORO'), ('PLATINO', 'PLATINO')], max_length=7)),
            ],
        ),
    ]
